name: app_shipper
description: A new Flutter project.

publish_to: "none"

version: 1.0.38+39

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_easyloading: ^3.0.5
  dio: ^5.0.0
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.17
  flutter_svg: ^2.0.1
  image_picker: ^0.8.6+1
  tuple: ^2.0.1
  fluttertoast: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.0.2
  flutter_screenutil: ^5.6.1
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  retrofit: ^4.0.1
  dropdown_button2: ^1.9.2
  pull_to_refresh: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  device_info_plus: ^8.0.0
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  firebase_database: ^10.0.9
  flutter_datetime_picker: ^1.5.1
  url_launcher: ^6.1.9
  flutter_barcode_scanner: ^2.0.0
  flutter_local_notifications: ^13.0.0
  rxdart: ^0.27.7
  permission_handler: ^10.4.3
  share_plus: ^6.3.4
  flutter_native_splash: ^2.2.19
  path_provider: ^2.0.15
  gallery_saver: ^2.3.2
  collection: ^1.17.0
  image_gallery_saver: ^2.0.3
  expansion_widget: ^0.0.3
  firebase_remote_config: ^4.2.5
  package_info: ^2.0.2
  sentry_flutter: ^7.11.0
  flutter_advanced_switch: ^3.0.1
  tiengviet: ^1.0.0
  google_mobile_ads: ^4.0.0
  flutter_html: ^3.0.0-alpha.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator:
  build_runner: ^2.1.11
  flutter_gen_runner: ^5.2.0
  retrofit_generator: ^5.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher.jpg"

flutter_gen:
  output: lib/src/configs/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  background_image: "assets/images/aloshipper_splash.png"
  android_12:
    background_image: "assets/images/aloshipper_splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/svgs/deposit/
    - assets/svgs/menu/
    - assets/svgs/support/

  fonts:
    - family: BeVN
      fonts:
        # Header
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        # Title
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        # Subtitle regular
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 400
        # Subtitle medium
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        # Subtitle bold
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 600
        # Body regular
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 400
        # Body medium
        # Body bold
        # Sub-body regular
        # Sub-body medium
        # Sub-body bold
        # Description regular
        # Description medium
        # Description bold
        # Caption
        # Caption

        - asset: assets/fonts/BeVietnamPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        # Semi bold
        - asset: assets/fonts/BeVietnamPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
